import { Chain, Token } from "@/types/blockchain";

export const SUPPORTED_NETWORKS: Record<number, Chain> = {
  // EVM Chains
  1: {
    id: 1,
    name: "Ethereum",
    type: "EVM",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    color: "bg-blue-500",
    hashlockSupport: true,
    timelockSupport: true,
  },
  137: {
    id: 137,
    name: "Polygon",
    type: "EVM",
    nativeCurrency: { symbol: "MATIC", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    color: "bg-purple-500",
    timelockSupport: true,
  },
  42161: {
    id: 42161,
    name: "Arbitrum",
    type: "EVM",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    color: "bg-blue-400",
    timelockSupport: true,
  },
  56: {
    id: 56,
    name: "BSC",
    type: "EVM",
    nativeCurrency: { symbol: "BNB", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    color: "bg-yellow-500",
    hashlockSupport: true,
    timelockSupport: true,
  },
  43114: {
    id: 43114,
    name: "Avalanche",
    type: "EVM",
    nativeCurrency: { symbol: "AVAX", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    color: "bg-red-500",
    timelockSupport: true,
  },
  10: {
    id: 10,
    name: "Optimism",
    type: "EVM",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    color: "bg-red-400" ,
    timelockSupport: true,
  },
  250: {
    id: 250,
    name: "Fantom",
    type: "EVM",
    nativeCurrency: { symbol: "FTM", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
     color: "bg-blue-600" 
  },

  // Non-EVM Chains with Hashlock/Timelock Support
  101: {
    id: 101,
    name: "Sui",
    type: "non-EVM",
    nativeCurrency: { symbol: "SUI", decimals: 9 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  102: {
    id: 102,
    name: "Aptos",
    type: "non-EVM",
    nativeCurrency: { symbol: "APT", decimals: 8 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  103: {
    id: 103,
    name: "Near",
    type: "non-EVM",
    nativeCurrency: { symbol: "NEAR", decimals: 24 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  104: {
    id: 104,
    name: "Starknet",
    type: "non-EVM",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  195: {
    id: 195,
    name: "Tron",
    type: "non-EVM",
    nativeCurrency: { symbol: "TRX", decimals: 6 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  196: {
    id: 196,
    name: "Ton",
    type: "non-EVM",
    nativeCurrency: { symbol: "TON", decimals: 9 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  197: {
    id: 197,
    name: "Bitcoin",
    type: "non-EVM",
    nativeCurrency: { symbol: "BTC", decimals: 8 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  198: {
    id: 198,
    name: "Cardano",
    type: "non-EVM",
    nativeCurrency: { symbol: "ADA", decimals: 6 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  199: {
    id: 199,
    name: "Stellar",
    type: "non-EVM",
    nativeCurrency: { symbol: "XLM", decimals: 7 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  200: {
    id: 200,
    name: "XRP Ledger",
    type: "non-EVM",
    nativeCurrency: { symbol: "XRP", decimals: 6 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  201: {
    id: 201,
    name: "Polkadot",
    type: "non-EVM",
    nativeCurrency: { symbol: "DOT", decimals: 10 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  202: {
    id: 202,
    name: "Cosmos Hub",
    type: "non-EVM",
    nativeCurrency: { symbol: "ATOM", decimals: 6 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
  203: {
    id: 203,
    name: "Tezos",
    type: "non-EVM",
    nativeCurrency: { symbol: "XTZ", decimals: 6 },
    rpcUrls: [],
    blockExplorerUrls: [],
    hashlockSupport: true,
    timelockSupport: true,
  },
};


export const POPULAR_TOKENS: Record<number, Token[]> = {
  1: [
    {
      address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      symbol: "ETH",
      name: "Ethereum",
      decimals: 18,
      logoURI: "",
      balance: "2.5",
    },
    {
      address: "0xA0b86a33E6441b6c4e8b36f9ccc5b47e12e6a1D5",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      logoURI: "",
      balance: "1500.0",
    },
    {
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      symbol: "USDT",
      name: "Tether",
      decimals: 6,
      logoURI: "",
      balance: "0.0",
    },
  ],
  137: [
    {
      address: "0x0000000000000000000000000000000000001010",
      symbol: "MATIC",
      name: "Polygon",
      decimals: 18,
      logoURI: "",
      balance: "1250.0",
    },
    {
      address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      logoURI: "",
      balance: "500.0",
    },
  ],
  101: [
    {
      address: "0x0::sui::SUI",
      symbol: "SUI",
      name: "Sui",
      decimals: 9,
      logoURI: "",
      balance: "1000.0",
    },
    {
      address: "0x0::usdc::USDC",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      logoURI: "",
      balance: "2500.0",
    },
  ],
  102: [
    {
      address: "0x1::aptos_coin::AptosCoin",
      symbol: "APT",
      name: "Aptos",
      decimals: 8,
      logoURI: "",
      balance: "500.0",
    },
    {
      address: "0x1::usdc::USDC",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      logoURI: "",
      balance: "1000.0",
    },
  ],
};